import { Geist, Geist_Mono } from "next/font/google";
import "../styles/style.css";
import Navbar from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mingla by YRGO",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
      <html lang="sv">
          <body>
              <Navbar />
              {children}
          </body>
      </html>
  );
}
